
//----------------------------------------------------
// The following code was generated by jh-javacup-1.0 20160720
// Fri Feb 08 19:38:49 GMT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class TokenNames {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int SEMICOLON = 2;
  public static final int ARRAY = 3;
  public static final int CLASS = 4;
  public static final int EXTENDS = 5;
  public static final int RETURN = 6;
  public static final int WHILE = 7;
  public static final int IF = 8;
  public static final int NEW = 9;
  public static final int LPAREN = 10;
  public static final int RPAREN = 11;
  public static final int LBRACK = 12;
  public static final int RBRACK = 13;
  public static final int LBRACE = 14;
  public static final int RBRACE = 15;
  public static final int NIL = 16;
  public static final int PLUS = 17;
  public static final int MINUS = 18;
  public static final int TIMES = 19;
  public static final int DIVIDE = 20;
  public static final int LT = 21;
  public static final int GT = 22;
  public static final int EQ = 23;
  public static final int ASSIGN = 24;
  public static final int COMMA = 25;
  public static final int DOT = 26;
  public static final int INT = 27;
  public static final int ID = 28;
  public static final int STRING = 29;
}

